apps:
  script: ./dist/main.js
  name: admin-server
  cwd: /data/apps/dstamp/admin-server/
  namespace: adm
  log_date_format: YYYY-MM-DD HH:mm:ss
  merge_logs: false
  stop_exit_codes: [0]
  # increment_var: PORT
  instances: 1
  env_test:
    # PORT: 3000
    NODE_ENV: test
  env_product:
    # PORT: 3000
    NODE_ENV: test
